Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.disksize.size = '10GB'

  config.vm.provider :virtualbox do |v, override|
    v.memory = 1024
    v.cpus = 1

    required_plugins = %w( vagrant-vbguest vagrant-disksize )
    required_plugins.each do |plugin|
      system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
    end
  end

  config.vm.provision 'shell', privileged: true, inline:
    "apt-get install -y python3 python3-pip libsdl2-2.0-0 xvfb x11vnc"

  config.vm.provision 'shell', privileged: true, inline:
    "pip3 install pyopengl imgui pysdl2"

end
